spring:
  application:
    name: communication-service
  mail:
    password: springboot
    username: duke
    host: 127.0.0.1
    port: 3025
    protocol: smtp
  data:
    mongodb:
      uri: mongodb://admin:communication-service@localhost:27017/communication-service?authSource=admin
  redis:
    host: localhost
    port: 6379
    password: communication-service

twilio:
  account-sid: AC23db9596312314f5bb30458c9aadd40
  auth-token: 0a5ccb07b51b2424123f312636f8100e26
  sender-phone-number: +19289166531
  url: http://127.0.0.1:8081/twilio

aws:
  access-key: 123secret
  secret-key: 123secret
  region: us-east-1
  sqs:
    email-queue-name: communication-sqs-email
    push-queue-name: communication-sqs-push
    sms-queue-name: communication-sqs-sms
    endpoint: http://localhost:4566/000000000000/
  s3:
    endpoint: http://localhost:4567

service-shared-secret: world
customer-auth-signing-secret: world

one-signal:
  auth-token: 123secret
  app-id: 111111-111111-111111
  url: http://127.0.0.1:8081/one-signal

ignore-generic-paths: /ws, /user/**/private

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yml