openapi: 3.0.0
info:
  title: "communication-service"
  version: 1.0.0
  description: >-
    Business management service.
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /email:
    post:
      tags:
        - Email
      description:
        Send one email
      operationId: sendOne
      security:
        - ServiceAuth: [ ]
      requestBody:
        required: true
        content:
          application/vnd.kaiqkt_email_v1+json:
            schema:
              $ref: '#/components/schemas/EmailV1'
      responses:
        204:
          description: Email sent with successfully
  /sms:
    post:
      tags:
        - Sms
      description:
        Send one sms
      operationId: sendOne
      security:
        - ServiceAuth: [ ]
      requestBody:
        required: true
        content:
          application/vnd.kaiqkt_sms_v1+json:
            schema:
              $ref: '#/components/schemas/SmsV1'
      responses:
        204:
          description: Sms sent with successfully
  /notification/{user_id}:
    post:
      tags:
        - Notification
      description:
        Send notification to user
      operationId: sendOne
      parameters:
        - name: user_id
          in: path
          description: id of a specific user
          required: true
          schema:
            type: string
      security:
        - ServiceAuth: [ ]
      requestBody:
        required: true
        content:
          application/vnd.kaiqkt_notification_v1+json:
            schema:
              $ref: '#/components/schemas/NotificationV1'
      responses:
        204:
          description: Sms sent with successfully
  /notification:
    get:
      tags:
        - Notification
      description:
        Get notifications for user
      operationId: find
      security:
        - CustomerAuth: [ ]
      responses:
        200:
          description: Get notification history successfully
          content:
            application/vnd.kaiqkt_notification_v1+json:
              schema:
                $ref: '#/components/schemas/NotificationHistoryV1'
        404:
          description: Notification history not found

components:
  schemas:
    SmsV1:
      type: object
      properties:
        recipient:
          type:
            string
        template:
          $ref: '#/components/schemas/TemplateV1'
      required:
        - recipient
        - template

    EmailV1:
      type: object
      properties:
        subject:
          type: string
        recipient:
          type: string
        template:
          $ref: '#/components/schemas/TemplateV1'
      required:
        - subject
        - recipient
        - template

    TemplateV1:
      type: object
      properties:
        url:
          type: string
        data:
          type: object
          additionalProperties:
            type: string
      required:
        - url
        - data

    NotificationV1:
      type: object
      properties:
        title:
          type: string
        body:
          type: string
      required:
        - title
        - recipient
        - body

    NotificationResponseV1:
      type: object
      properties:
        title:
          type: string
        body:
          type: string
        created_at:
          type: LocalDateTime
      required:
        - title
        - recipient
        - body
        - created_at

    NotificationHistoryV1:
      type: object
      properties:
        notifications:
          type: array
          items:
            $ref: '#/components/schemas/NotificationResponseV1'


    ErrorResponseV1:
      type: object
      properties:
        details:
          type: object

  securitySchemes:
    CustomerAuth:
      type: http
      scheme: bearer
    ServiceAuth:
      type: apiKey
      name: Authorization
      in: header