version: '2'
services:
  localstack:
    container_name: localstack-communication
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"            # LocalStack Gateway
      - "9090:9090"  # external services port range
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=123secret
      - AWS_ACCESS_KEY_ID=123secret
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    command: sh ./localstack/init-localstack.sh
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
      - ./localstack/storage:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock