version: '2'
services:
  communication-localstack:
    container_name: communication-localstack
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=123secret
      - AWS_ACCESS_KEY_ID=123secret
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    command: sh ./localstack/init-localstack.sh
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
      - ./localstack/storage:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - communication-service-network
  communication-mongodb:
    container_name: communication-mongodb
    image: mongo:3
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "communication-service"
      MONGO_INITDB_ROOT_USERNAME: "communication-service"
      MONGO_INITDB_ROOT_PASSWORD: "communication-service"
    volumes:
      - communication-mongo:/data/db
    networks:
      - communication-service-network
  communication-redis:
    container_name: communication-redis
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass 'communication-service'
    volumes:
      - communication-redis:/data/cache
    networks:
      - communication-service-network
  communication-service:
    depends_on:
      - communication-localstack
      - communication-mongodb
      - communication-redis
    container_name: communication-service
    image: communication-service
    ports:
      - "8080:8080"
    environment:
      MAIL_HOST: smtp.gmail.com
      MAIL_USERNAME: kaiqktt.dev@gmail.com
      MAIL_PASSWORD: hbpwyqtewkhohqse
      MONGO_HOST: communication-mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: communication-service
      MONGO_PASSWORD: communication-service
      MONGO_DATABASE: communication-service
      REDIS_HOST: communication-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: communication-service
      AWS_ACCESS_KEY: 123secret
      AWS_SECRET_KEY: 123secret
      AWS_REGION: us-east-1
      AWS_SQS_ENDPOINT:  http://communication-localstack:4566/000000000000/
      AWS_S3_ENDPOINT: http://communication-localstack:4566/
      AWS_SQS_EMAIL_QUEUE_NAME: communication-sqs-email
      AWS_SQS_SMS_QUEUE_NAME:  communication-sqs-sms
      TWILIO_ACCOUNT_SID: AC387ac913857615d82827c8075bace546
      TWILIO_AUTH_TOKEN: 25c02393f4feb601639cf418aa6c70a6
      TWILIO_SENDER_PHONE: +12067595631
      TWILIO_URL: https://api.twilio.com/2010-04-01
      SERVICE_SECRET: world
      CUSTOMER_AUTH_SECRET: world
    networks:
      - communication-service-network

networks:
  communication-service-network:
    driver: bridge

volumes:
  communication-mongo:
    driver: local
  communication-redis:
    driver: local
  communication-localstack:
    driver: local
  communication-service:
    driver: local